<?php
return [
    'Windows 10',
    'Windows 8.1',
    'Windows 8',
    'Windows 7',
    'Windows Vista',
    'Windows Server 2003/XP x64',
    'Windows 3.1',
    'Windows 95',
    'Windows 98',
    'Windows 2000',
    'Windows NT',
    'Windows XP',
    'Windows Vista',
    'Redhat Linux',
    'Ubuntu',
    'Fedora',
    'AmigaOS',
    'OS 10.5',
    'Mac OS X',
    'Mac OS 9',
    'Linux',
    'iPhone',
    'iPod',
    'iPad',
    'Android',
    'BlackBerry',
    'Mobile'
];